# Generated by Django 2.0 on 2017-12-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
