# Generated by Django 2.0 on 2017-12-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171219_1709'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('wallpaper', 'ip')},
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('wallpaper', 'ip')},
        ),
    ]
