# Generated by Django 2.0 on 2017-12-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171219_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='active',
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='status',
            field=models.CharField(default='Active', max_length=10),
            preserve_default=False,
        ),
    ]
