# Generated by Django 2.0 on 2017-12-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171226_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
