# Generated by Django 2.0 on 2017-12-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_wallpaper_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='logo_size',
            field=models.FloatField(default=1),
        ),
    ]
