# Generated by Django 2.0 on 2018-01-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_wallpaper_populate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
